version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0
      
    working_directory: ~/app

    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
